from ..plot import BINARY_COLORSCALE, CATEGORICAL_COLORSCALE, CONTINUOUS_COLORSCALE

TYPE_COLORSCALE = {
    "continuous": CONTINUOUS_COLORSCALE,
    "categorical": CATEGORICAL_COLORSCALE,
    "binary": BINARY_COLORSCALE,
}
