from .linear_model.linear_model.correlate import correlate
from .probability.probability.infer_assuming_independence import infer_assuming_independence
from .probability.probability.compute_joint_probability import compute_joint_probability
from .probability.probability.plot_bayesian_nomogram import plot_bayesian_nomogram
from .probability.probability.infer import infer
from .probability.probability.compute_posterior_probability import compute_posterior_probability
from .probability.probability.get_target_grid_indices import get_target_grid_indices
from .support.support.json_ import read_json
from .support.support.json_ import write_json
from .support.support.exit_ import exit_
from .support.support.dict_ import merge_dicts_with_function
from .support.support.dict_ import write_dict
from .support.support.volume import get_volume_name
from .support.support.volume import make_volume_dict
from .support.support.volume import mount
from .support.support.volume import unmount
from .support.support.environment import get_shell_environment
from .support.support.environment import install_libraries
from .support.support.environment import get_reference
from .support.support.series import cast_series_to_builtins
from .support.support.series import make_membership_df_from_categorical_series
from .support.support.series import get_top_and_bottom_series_indices
from .support.support.series import simulate_series
from .support.support.iterable import group
from .support.support.iterable import flatten_nested
from .support.support.iterable import replace_bad_objects
from .support.support.iterable import integize
from .support.support.iterable import group_and_apply_function_on_each_group
from .support.support.iterable import get_unique_objects_in_order
from .support.support.network import download
from .support.support.network import get_open_port
from .support.support.subprocess_ import run_command
from .support.support.subprocess_ import run_command_and_monitor
from .support.support.df import drop_df_slices
from .support.support.df import split_df
from .support.support.df import simulate_df
from .support.support.path import establish_path
from .support.support.path import copy_path
from .support.support.log import get_now
from .support.support.log import initialize_logger
from .support.support.log import secho_with_random_color
from .support.support.system import shutdown
from .support.support.system import reboot
from .support.support.str_ import title_str
from .support.support.str_ import untitle_str
from .support.support.str_ import cast_str_to_builtins
from .support.support.str_ import split_str_ignoring_inside_quotes
from .support.support.multiprocess import multiprocess
from .support.support.git import create_gitkeep
from .support.support.compression import unzip
from .support.support.compression import extract_tar
from .support.support.compression import gzip_compress
from .support.support.compression import gzip_decompress
from .support.support.compression import gzip_decompress_and_bgzip_compress
from .mutational_signature.mutational_signature.mutational_signature import compute_apobec_mutational_signature_enrichment
from .match.match.make_summary_match_panel import make_summary_match_panel
from .match.match.make_comparison_panel import make_comparison_panel
from .match.match.plot_match_panel import plot_match_panel
from .match.match.match import match
from .match.match.match import match_randomly_sampled_target_and_features_to_compute_margin_of_errors
from .match.match.match import permute_target_and_match_target_and_features
from .match.match.match import match_target_and_features
from .match.match.make_match_panel import make_match_panel
from .file.file.read_fpkm_tracking import read_fpkm_tracking
from .file.file.access_gmt import read_gmts
from .file.file.access_gmt import write_gmt
from .file.file.access_gct import read_gct
from .file.file.access_gct import write_gct
from .information.information.compute_entropy import compute_entropy
from .information.information.compute_information_coefficient import compute_information_distance
from .information.information.compute_information_coefficient import compute_information_coefficient
from .information.information.compute_brier_entropy import compute_brier_entropy
from .plot.plot.plot_nmf import plot_nmf
from .plot.plot.save_plot import save_plot
from .plot.plot.plot_points import plot_points
from .plot.plot.make_random_color import make_random_color
from .plot.plot.assign_colors import assign_colors
from .plot.plot.make_random_categorical_colormap import make_random_categorical_colormap
from .plot.plot.plot_heatmap import plot_heatmap
from .plot.plot.get_ax_positions_relative_to_figure import get_ax_positions_relative_to_figure
from .plot.plot.plot_clustermap import plot_clustermap
from .plot.plot.plot_samples import plot_samples
from .plot.plot.plot_violin_box_or_bar import plot_violin_box_or_bar
from .plot.plot.plot_lines import plot_lines
from .plot.plot.plot_columns import plot_columns
from .plot.plot.get_ax_positions_relative_to_ax import get_ax_positions_relative_to_ax
from .plot.plot.make_categorical_colormap import make_categorical_colormap
from .plot.plot.decorate import decorate
from .plot.plot.plot_distribution import plot_distribution
from .nd_array.nd_array.make_index_and_fraction_grid_coordinates_pair import make_index_and_fraction_grid_coordinates_pair
from .nd_array.nd_array.drop_nan_and_apply_function_on_2_1d_arrays import drop_nan_and_apply_function_on_2_1d_arrays
from .nd_array.nd_array.make_nd_grid_coordinates import make_nd_grid_coordinates
from .nd_array.nd_array.shuffle_each_2d_array_slice import shuffle_each_2d_array_slice
from .nd_array.nd_array.normalize_2d_array import normalize_2d_array
from .nd_array.nd_array.define_exponential_function import define_exponential_function
from .nd_array.nd_array.compute_empirical_p_values_and_fdrs import compute_empirical_p_values_and_fdrs
from .nd_array.nd_array.compute_margin_of_error import compute_margin_of_error
from .nd_array.nd_array.apply_function_on_2_2d_arrays_slices import apply_function_on_2_2d_arrays_slices
from .nd_array.nd_array.normalize_1d_array import normalize_1d_array
from .nd_array.nd_array.fit_function_on_each_2d_array_slice import fit_function_on_each_2d_array_slice
from .nd_array.nd_array.get_1d_array_unique_objects_in_order import get_1d_array_unique_objects_in_order
from .nd_array.nd_array.apply_function_on_2_1d_arrays_and_compute_empirical_p_value import apply_function_on_2_1d_arrays_and_compute_empirical_p_value
from .nd_array.nd_array.compute_log2_ratios import compute_log2_ratios
from .nd_array.nd_array.cluster_2d_array_slices_by_group import cluster_2d_array_slices_by_group
from .nd_array.nd_array.compute_empirical_p_value import compute_empirical_p_value
from .nd_array.nd_array.cluster_2d_array_rows import cluster_2d_array_rows
from .onco_gps.onco_gps.make_node_x_dimension import make_node_x_dimension
from .onco_gps.onco_gps.make_grid_values_and_continuous_phenotypes import make_grid_values_and_continuous_phenotypes
from .onco_gps.onco_gps.define_states import define_states
from .onco_gps.onco_gps.make_sample_x_dimension import make_sample_x_dimension
from .onco_gps.onco_gps.make_grid_values_and_categorical_phenotypes import make_grid_values_and_categorical_phenotypes
from .onco_gps.onco_gps.solve_for_nmf_h import solve_for_nmf_h
from .onco_gps.onco_gps.define_components import define_components
from .onco_gps.onco_gps.GPSMap import GPSMap
